version: "2"

services:
  kafka2influxdb:
    build: .
    volumes:
    - ./kafka2influxdb.toml:/etc/kafka2influxdb/kafka2influxdb.toml
    depends_on:
    - zookeeper
    - broker
    - influxdb
    command: ["start","--loglevel=debug"]
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181
    logging:
      driver: none

  broker:
    image: confluentinc/cp-kafka:3.2.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://broker:9092
    depends_on: [zookeeper]
    depends_on:
    - zookeeper

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
    - 8083:8083
    - 8086:8086
    - 8090:8090
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
